name: test
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: test
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run Tests
        run: just test
